# Generated by Django 3.1.1 on 2020-10-04 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('create_Date', models.DateTimeField()),
                ('drawing_Filter', models.TextField()),
                ('category', models.CharField(choices=[('우울', '우울'), ('학업', '학업')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tr_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
                ('trouble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trouble.trouble')),
            ],
        ),
    ]
